name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, macos-latest]
        otp_version: [24.3.1, 25.2.1, 26.1.1]
        exclude:
          - os: macos-latest
            otp_version: 24.3.1
          - os: macos-latest
            otp_version: 25.2.1
          - os: macos-latest
            otp_version: 26.1.1
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up OTP
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libsasl2-dev liblz4-dev libzstd-dev

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install erlang openssl@1.1 lz4 zstd curl
      env:
        HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: true
        HOMEBREW_NO_INSTALL_UPGRADE: true
        HOMEBREW_NO_INSTALL_CLEANUP: true

    - name: Download rebar3
      run: |
        curl https://s3.amazonaws.com/rebar3/rebar3 --output rebar3
        chmod +x rebar3

    - name: Compile project
      run: ./rebar3 compile
